/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context as Context } from "./context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  Role: "FREE" | "SUBSCRIBED"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Category: { // root type
    id: string; // String!
    name: string; // String!
  }
  Comment: { // root type
    content: string; // String!
    id: string; // String!
    userId: string; // String!
  }
  Favorite: { // root type
    id: string; // String!
    userId: string; // String!
  }
  Mutation: {};
  Post: { // root type
    about: string; // String!
    destination: string; // String!
    favoriteId?: string | null; // String
    id: string; // String!
    title: string; // String!
    userId: string; // String!
  }
  Query: {};
  User: { // root type
    email: string; // String!
    id: string; // String!
    image: string; // String!
    name: string; // String!
    role: NexusGenEnums['Role']; // Role!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Category: { // field return type
    id: string; // String!
    name: string; // String!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
  }
  Comment: { // field return type
    content: string; // String!
    id: string; // String!
    post: NexusGenRootTypes['Post'] | null; // Post
    user: NexusGenRootTypes['User']; // User!
    userId: string; // String!
  }
  Favorite: { // field return type
    id: string; // String!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    user: NexusGenRootTypes['User']; // User!
    userId: string; // String!
  }
  Mutation: { // field return type
    createUser: NexusGenRootTypes['User']; // User!
  }
  Post: { // field return type
    about: string; // String!
    categories: NexusGenRootTypes['Category'][]; // [Category!]!
    comments: NexusGenRootTypes['Comment'][]; // [Comment!]!
    destination: string; // String!
    favoriteId: string | null; // String
    id: string; // String!
    title: string; // String!
    user: NexusGenRootTypes['User'] | null; // User
    userId: string; // String!
  }
  Query: { // field return type
    getUser: NexusGenRootTypes['User'] | null; // User
    users: NexusGenRootTypes['User'][] | null; // [User!]
  }
  User: { // field return type
    comments: NexusGenRootTypes['Comment'][]; // [Comment!]!
    email: string; // String!
    favorites: NexusGenRootTypes['Favorite'][] | null; // [Favorite!]
    id: string; // String!
    image: string; // String!
    name: string; // String!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    role: NexusGenEnums['Role']; // Role!
  }
}

export interface NexusGenFieldTypeNames {
  Category: { // field return type name
    id: 'String'
    name: 'String'
    posts: 'Post'
  }
  Comment: { // field return type name
    content: 'String'
    id: 'String'
    post: 'Post'
    user: 'User'
    userId: 'String'
  }
  Favorite: { // field return type name
    id: 'String'
    posts: 'Post'
    user: 'User'
    userId: 'String'
  }
  Mutation: { // field return type name
    createUser: 'User'
  }
  Post: { // field return type name
    about: 'String'
    categories: 'Category'
    comments: 'Comment'
    destination: 'String'
    favoriteId: 'String'
    id: 'String'
    title: 'String'
    user: 'User'
    userId: 'String'
  }
  Query: { // field return type name
    getUser: 'User'
    users: 'User'
  }
  User: { // field return type name
    comments: 'Comment'
    email: 'String'
    favorites: 'Favorite'
    id: 'String'
    image: 'String'
    name: 'String'
    posts: 'Post'
    role: 'Role'
  }
}

export interface NexusGenArgTypes {
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}